# Generated by Django 5.2.9 on 2025-12-14 23:27

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioAdm',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionário Administrativo',
                'verbose_name_plural': 'Funcionários Administrativos',
                'db_table': 'academico_funcionarioadm',
            },
            bases=('core.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='cronograma',
            name='descricao',
            field=models.CharField(default='Cronograma Padrão', max_length=200),
        ),
        migrations.AddField(
            model_name='monitor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitores', to='core.turma'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='conteudo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
